export enum DocumentStatus {
  PENDING = 'PENDING',
  UPLOADING = 'UPLOADING',
  CLASSIFYING = 'CLASSIFYING',
  PARSING = 'PARSING',
  EXTRACTING = 'EXTRACTING',
  VALIDATING = 'VALIDATING',
  RESOLVING = 'RESOLVING',
  LOADING = 'LOADING',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
}

export enum DocumentType {
  FORM_1040 = 'FORM_1040',
  BANK_STATEMENT = 'BANK_STATEMENT',
  CLOSING_DISCLOSURE = 'CLOSING_DISCLOSURE',
  UUTS = 'UUTS',
  VOI = 'VOI',
  LETTER_OF_EXPLANATION = 'LETTER_OF_EXPLANATION',
  PAY_STUB = 'PAY_STUB',
  ALTA_TITLE = 'ALTA_TITLE',
  W2 = 'W2',
  UNKNOWN = 'UNKNOWN',
}

export enum ParsePath {
  TEXT = 'TEXT',
  VISION = 'VISION',
}
