export enum IncomeType {
  W2 = 'W2',
  SELF_EMPLOYMENT = 'SELF_EMPLOYMENT',
  RENTAL = 'RENTAL',
  PENSION = 'PENSION',
  SOCIAL_SECURITY = 'SOCIAL_SECURITY',
  OTHER = 'OTHER',
}

export enum AccountType {
  CHECKING = 'CHECKING',
  SAVINGS = 'SAVINGS',
  INVESTMENT = 'INVESTMENT',
  RETIREMENT = 'RETIREMENT',
  OTHER = 'OTHER',
}
